### ISSUE TITLE
VISS 2 wide review tracking

### ISSUE THREAD

**Issue by caribouW3** [w3c/automotive#455]
- [x]  [Accessibility review](https://github.com/w3c/a11y-request/issues/38)
- [x] [Internationalization review](https://github.com/w3c/i18n-request/issues/191)
- [ ] [TAG review](https://github.com/w3ctag/design-reviews/issues/768)
- [ ] [security review](https://github.com/w3c/security-request/issues/39)
- [ ] [privacy review](https://github.com/w3cping/privacy-request/issues/102)
